project:
  type: website

website:
  title: "Seth B. Morgan"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: resumecv.qmd
        text: Resume/CV
      - href: projects.qmd
        text: Coding Projects
      - href: farmlife.qmd
        text: Farm Life
      - href: photography.qmd
        text: Photography        
    tools:
      - icon: github
        href: https://github.com/sbmorgan
      - icon: linkedin
        href: https://www.linkedin.com/in/sethbmorgan/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

