project:
  type: website

website:
  title: "Seth B. Morgan"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: resumecv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: tbf.qmd
        text: The Brosey Farm
      - href: photography.qmd
        text: Photography        
    tools:
      - icon: github
        href: https://github.com/sbmorgan
      - icon: linkedin
        href: https://www.linkedin.com/in/sethbmorgan/
  repo-url: https://github.com/sbmorgan/sbm_portfolio
  repo-subdir: website_quarto
  repo-actions: [source]

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

