---
#title: "About"
# about:
#   template: jolla
format:
  html:
    page-layout: article

---

## Bio

I grew up in a small rural town in SW Ohio working at a local tree and shrub nursery during the summers between academic grade school years. My love of education and plants led to a B.S. in Agriculture (major: Agribusiness & Applied Economics) with minors in horticulture and Spanish from The Ohio State University in 2001. 

During my last year at Ohio State, I studied abroad in Guanajuato, Mexico during which time I became interested in international development. After a few years working in the nursery industry after completing my undergraduate degree, I decided to return to Latin America to work for Guatemalan NGOs working in the education and agariculture sectors. After this stint abroad, I went on to earn a M.A. in International & Development Economics from the University of San Francisco in 2008, which included overseas field study in Huehuetenango, Guatemala. I subsequently presented my master’s thesis developed from this filed study at the Pacific Conference for Development Economics (PacDev) at the Univerity of California San Diego (UCSD). 

After completing my graduate degree, my career intially focused on evaluating international development programs in the education and agriculture sectors, particularly data analysis using Stata at the research consultancy firm Mathematica (https://www.mathematica.org/). However, to more comprehensively contibute to the evaluation designs of these evaluation projects, I became certified in What Works Clearinghouse group design standards in 2014 which expanded my work portfolio to include the evaluation of domestic education public policy and WWC systematic review efforts funded by the Institute of Ecuation Sciences (IES) for the development practice guides, evidence-based recommendations for educators to improve student outcomes (https://ies.ed.gov/ncee/WWC/Search/Products?productType=1). 

About 3 years ago I decided to transition to perform my portfolio of work as a freelance consultant to have more time and flexibility to work on restoring my family's legacy farm, The Brosey Farm, which I purchased upon my grandmother's passing roughly 5 years ago. [Current R projects -> title link  in portfolio]

My full CV can be found [here](documents/resume_Seth_B_Morgan_2026.pdf){target="_blank"}

## Education

-   M.A. in International & Development Economics, University of San Francisco, 2008

-   B.S. in Agriculture (Major: Agribusiness & Applied Economics; Minors: Horticulture, Spanish), The Ohio State University, 2001

## Notable skills

-   Statistical Data Analysis · Statistical Programming (Stata, R)

-   Evaluation Design · Impact Analysis · Meta-analysis · Systematic Reviews

-   Organic market farming · Farm business development · Sustainable agriculture

-   Spanish (read, write, and speak proficiently)

## Certifications

-   Human Subjects Research – Social-Behavioral-Educational (SBE) Foundations
    CITI Program- Issued Dec 2025 · Expires Dec 2026

-   WWC Reviewer Certification, Single-Case Design Standards (SCD), Version 5.0
    What Works Clearinghouse (WWC), Institute of Education Sciences (IES)- Issued Apr 2024

-   WWC Reviewer Certification, Group Design Standards (GDS), Version 5.0
    What Works Clearinghouse (WWC), Institute of Education Sciences (IES)- Issued May 2023

-   WWC Reviewer Certification, Regression Discontinuity Design (RDD) Standards, Version 4.1
    What Works Clearinghouse (WWC), Institute of Education Sciences (IES)- Issued May 2022

-   Certified Evidence Reviewer, Home Visiting Evidence of Effectiveness Review (HomVEE)

## Contact Info

-   {{< fa phone size=2x >}} Cell: +1 415-948-8277

-   {{< fa envelope size=2x >}} Email: seth.b.morgan\@outlook.com

-   {{< fa brands github size=2x >}} GitHub: <https://github.com/sbmorgan>

-   {{< fa brands linkedin size=2x >}} LinkedIn: <https://www.linkedin.com/in/sethbmorgan/>
